[package]
name = "rmls"
version = "0.0.0"
edition = "2021"
authors = ["Rusty Rain <y@liu.mx>"]
description = "MLS in Rust"
license = "MIT/Apache-2.0"
repository = "https://github.com/ngr-tc/rmls"

[dependencies]
